language: node_js

node_js:
  - 0.8

before_script:
  - git clone https://github.com/alipay/liquidluck-theme-arale2.git ../liquidluck-theme-arale2
  - cp -r ../liquidluck-theme-arale2/static tests/
  - cp -r ../liquidluck-theme-arale2/templates tests/
  - cp -r ../liquidluck-theme-arale2/test-travis.js tests/
  - nohup node tests/test-travis.js &

install: 
  - npm install spm node-static swig phantomjs
  - echo "{\"sources\": [\"http://modules.aralejs.org\", \"http://modules.seajs.org\"]}" > ~/.spm/config.json
  - spm install
  
script: ./node_modules/.bin/phantomjs tests/static/js/run_jasmine_test.coffee http://127.0.0.1:8000/tests/runner.html
